// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project1_EntityFramework.Data;

#nullable disable

namespace Project1_EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project1_EntityFramework.Entities.Clint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Clints", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Cairo",
                            Name = "Mahmoud"
                        },
                        new
                        {
                            Id = 2,
                            Country = "Qena",
                            Name = "Ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Country = "BaniSwif",
                            Name = "Mariam"
                        },
                        new
                        {
                            Id = 4,
                            Country = "Asuit",
                            Name = "Osama"
                        },
                        new
                        {
                            Id = 5,
                            Country = "Giza",
                            Name = "Yousif"
                        });
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Cairo",
                            Name = "IT"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Qena",
                            Name = "CS"
                        },
                        new
                        {
                            Id = 3,
                            Location = "BaniSwif",
                            Name = "AI"
                        },
                        new
                        {
                            Id = 4,
                            Location = "Asuit",
                            Name = "IS"
                        },
                        new
                        {
                            Id = 5,
                            Location = "Giza",
                            Name = "QQ"
                        });
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            DepartmentId = 1,
                            Name = "Mahmoud",
                            Salary = 10000m,
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            DepartmentId = 2,
                            Name = "Ahmed",
                            Salary = 15000m,
                            Status = true
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            DepartmentId = 1,
                            Name = "Sara",
                            Salary = 12000m,
                            Status = false
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            DepartmentId = 3,
                            Name = "Mona",
                            Salary = 20000m,
                            Status = true
                        });
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Budget")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.Property<int?>("ClintId")
                        .HasColumnType("int");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("VARCHAR");

                    b.HasKey("Id");

                    b.HasIndex("ClintId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Projects", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Budget = 50000m,
                            ClintId = 1,
                            DepartmentId = 1,
                            Name = "E-Commerce System"
                        },
                        new
                        {
                            Id = 2,
                            Budget = 80000m,
                            ClintId = 2,
                            DepartmentId = 3,
                            Name = "AI Chatbot"
                        },
                        new
                        {
                            Id = 3,
                            Budget = 60000m,
                            ClintId = 1,
                            DepartmentId = 2,
                            Name = "University Portal"
                        });
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Employee", b =>
                {
                    b.HasOne("Project1_EntityFramework.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("Project1_EntityFramework.Entities.Project", "Project")
                        .WithMany("Employees")
                        .HasForeignKey("ProjectId");

                    b.Navigation("Department");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Project", b =>
                {
                    b.HasOne("Project1_EntityFramework.Entities.Clint", "Clint")
                        .WithMany("Projects")
                        .HasForeignKey("ClintId");

                    b.HasOne("Project1_EntityFramework.Entities.Department", "Department")
                        .WithMany("Projects")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Clint");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Clint", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Project1_EntityFramework.Entities.Project", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
